cache:
  directories:
  - "$HOME/.cache/pip"
language: python
matrix:
  include:
  - python: '2.6'
    env: TOXENV=py26
  - python: '2.7'
    env: TOXENV=py27
  - python: '3.4'
    env: TOXENV=py34
  - python: '3.5'
    env: TOXENV=py35
  - python: '2.7'
    env: TOXENV=pep8
before_install:
  - pip install --upgrade pip
  - pip install --upgrade tox codecov
script:
  - tox
after_success:
  - coverage combine
  - codecov
